apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vcluster-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.loft.sh
    chart: vcluster
    targetRevision: 0.36.1
    helm:
      releaseName: vcluster
      values: |
        telemetry:
          enabled: false
  destination:
    namespace: vcluster
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 30s
        maxDuration: 5m
        factor: 2
