---
apiVersion: v1
kind: Service
metadata:
  name: vpa-recommender
  namespace: kube-system
  labels:
    app: vpa-recommender
spec:
  selector:
    app.kubernetes.io/name: vertical-pod-autoscaler
    app.kubernetes.io/instance: vertical-pod-autoscaler
    app.kubernetes.io/component: recommender
  ports:
    - name: prometheus
      port: 8942
      targetPort: prometheus
