---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: k8s-monitoring-alloy-metrics
  namespace: grafana-cloud
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: k8s-monitoring-alloy-metrics
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: k8s-monitoring-alloy-logs
  namespace: grafana-cloud
spec:
  targetRef:
    apiVersion: apps/v1
    kind: DaemonSet
    name: k8s-monitoring-alloy-logs
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: k8s-monitoring-kube-state-metrics
  namespace: grafana-cloud
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: k8s-monitoring-kube-state-metrics
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: k8s-monitoring-node-exporter
  namespace: grafana-cloud
spec:
  targetRef:
    apiVersion: apps/v1
    kind: DaemonSet
    name: k8s-monitoring-node-exporter
  updatePolicy:
    updateMode: "Off"
