---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: hubble-observer
  namespace: hubble-observer
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hubble-observer
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: hubble-observer-cf2cnp
  namespace: hubble-observer
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hubble-observer-cf2cnp
  updatePolicy:
    updateMode: "Off"
