---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: longhorn-driver-deployer
  namespace: longhorn-system
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: longhorn-driver-deployer
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: longhorn-ui
  namespace: longhorn-system
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: longhorn-ui
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: longhorn-manager
  namespace: longhorn-system
spec:
  targetRef:
    apiVersion: apps/v1
    kind: DaemonSet
    name: longhorn-manager
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: longhorn-csi-plugin
  namespace: longhorn-system
spec:
  targetRef:
    apiVersion: apps/v1
    kind: DaemonSet
    name: longhorn-csi-plugin
  updatePolicy:
    updateMode: "Off"
