apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    chart: external-dns
    targetRevision: 1.21.1
    helm:
      releaseName: external-dns
      values: |
        provider: cloudflare
        sources:
          - service
          - gateway-httproute
        domainFilters:
          - icaninto.space
        policy: sync
        registry: txt
        txtOwnerId: homelab
        serviceMonitor:
          enabled: true
        env:
          - name: CF_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: cloudflare-api-token
                key: cloudflare-api-token
  destination:
    namespace: external-dns
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
