apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gha-runner-scale-set-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set
    targetRevision: 0.14.2
    path: .
    helm:
      releaseName: gha-runner-scale-set
      values: |
        githubConfigUrl: "https://github.com/infrabytes/"
        githubConfigSecret: arc-runner-auth
        controllerServiceAccount:
          name: gha-runner-scale-set-controller-app-gha-rs-controller
          namespace: arc-systems
        runnerScaleSetName: argocd-diff-runner
        runnerGroup: homelab
        template:
          spec:
            serviceAccountName: arc-runner
            automountServiceAccountToken: true
            volumes:
              - name: tool-cache
                persistentVolumeClaim:
                  claimName: gha-runner-tool-cache
            initContainers:
              - name: tool-cache-dirs
                image: alpine:3.24
                securityContext:
                  allowPrivilegeEscalation: false
                command:
                  - /bin/sh
                  - -c
                  - |
                    mkdir -p /opt/tool-cache/runner
                    chown -R 1000:1000 /opt/tool-cache/runner
                volumeMounts:
                  - name: tool-cache
                    mountPath: /opt/tool-cache
            containers:
              - name: runner
                image: ghcr.io/actions/actions-runner:latest
                command: ["/home/runner/run.sh"]
                volumeMounts:
                  - name: tool-cache
                    mountPath: /opt/tool-cache
                env:
                  - name: RUNNER_TOOL_CACHE
                    value: /opt/tool-cache/runner
                  - name: PATH
                    value: "/opt/tool-cache/manual/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  destination:
    namespace: arc-runners
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
